version: '3.8'

services:
  mysql:
    container_name: simplecms-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simplecms
      MYSQL_USER: simplecms
      MYSQL_PASSWORD: simplecms
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
